
name-template: v$NEXT_PATCH_VERSION
tag-template: 'v$NEXT_PATCH_VERSION'
version-template: '$MAJOR.$MINOR.$PATCH.*'
categories:
  - title: 🚀 Features
    label: 'feat'
  - title: 🐛 Bug Fixes
    label: 'fix'
  - title: 🧰 Maintenance
    label: chore
change-template: $TITLE @$AUTHOR (#$NUMBER)
template: |
  ## Changes

  $CHANGES
